variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build

docker_build:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg SSH_PRIVATE_KEY="$timhsu_key" -t $IMAGE_TAG -t $LATEST_TAG .
    - docker push --all-tags $CI_REGISTRY_IMAGE
    - docker rmi $IMAGE_TAG $LATEST_TAG
    - docker system prune --volumes -f
